
print("Hey, let's go on a fun adventure!!!!!")
print("16 questions, 1 story, let's goooo!!")
print(" ")

color = input("1. What is your favourite color? ")
lyemotion = input("2. Give me an emotion ending with \"ly\": ")
verb1 = input("3. Give me a verb in past tense?: ")
sweet = input("4. How does sugar taste like (one word)? ")
favfood = input("5. What is your favourite food? ")
favsong = input("6. What is your favourite song? ")
favband = input("7. Who is your favourite artiste or band? ")
job = input("8. Favourive hobby: ")
time = input("9. What time is it? ")
verb2 = input("10. Give me another verb: ")
adj2 = input("11. Give me another adjective: ")
favfood2 = input("12. What did you say your favourite food was? ")
emotion = input("13. Give me any emotion? ")
ingverb = input("14. Verb ending with \"ing\": ")
activity = input("15. Your favourite activity? ")
curseword = input("16. I need a curse word ending with \"ing\": ")
curseword = curseword.upper()

print(" ")
print("Walking through the " + color + " door.")
print("I " + lyemotion + " stormed over to the kitchen and " + verb1 + " a")
print(sweet + " amount of " + favfood + " and my old copy of " + favsong)
print("By " + favband + " and " + job + " myself in the bedroom")
print("After about " + time + " I " + verb2 + " up my ceilling, then over at" )
print("The " + adj2 + " container of " + favfood2 + " ; and as the realization")
print("Of what had happened earlier, tears of " + emotion + " began " + ingverb)
print("Down my face. I'm going to tell this now, " + activity + " " + curseword + " sucks!!!")